app:
    resource: "@AppBundle/Controller/"
    type:     annotation

api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation
    prefix:   "/api/"

legacy:
    resource: .
    type: phpfiles
