# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        #public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    AppBundle\Twig\:
        resource: '../../src/AppBundle/Twig'
        autowire: true
        autoconfigure: true

    AppBundle\Chat\:
        resource: '../../src/AppBundle/Chat'
        autowire: true
        autoconfigure: true

    AppBundle\Serializer\:
        resource: '../../src/AppBundle/Serializer'
        autowire: true
        autoconfigure: true

    AppBundle\Http\:
        resource: '../../src/AppBundle/Http'
        autowire: true
        autoconfigure: true

    #AppBundle\Services\:
        #resource: '../../src/AppBundle/Services/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        #exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    #AppBundle\:
        #resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        #exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'

    messaging_service:
      class: 'AppBundle\Services\MessagingService'
      autowire: true

    AppBundle\Twig\CachebustExtension:
        arguments:
          $webpath: '%kernel.project_dir%/web'

    AppBundle\Services\ConfigService:
      arguments:
        $config: "%config%"

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    legacy_cookie_authenticator:
        class: AppBundle\Security\LegacyCookieAuthenticator
        autowire: true

    legacy_cookie_setter:
        class: AppBundle\Security\LegacyCookieSetter
        arguments: ['%host%']

    legacy_route_loader:
        class: AppBundle\Services\LegacyRouteLoader
        arguments: ['%karoroot%']
        tags:
          - { name: routing.loader }

    legacy_chatline_converter:
        class: AppBundle\Services\LegacyChatlineConverter
        arguments:
        - '@smilifier'

    visit_log:
        class: AppBundle\Services\VisitLogService
        autowire: true
        tags:
          - { name: kernel.event_listener, event: security.authentication.success}

    karo_query:
        class: AppBundle\Services\KaroQuery
        autowire: true

    user_repository:
      class: Doctrine\ORM\EntityRepository
      factory: ['@doctrine.orm.default_entity_manager', getRepository]
      arguments:
          - 'AppBundle:User'

    user_distance_calculator:
      class: AppBundle\Services\User\DistanceCalculator
      autowire: true

    game_loader:
      class: AppBundle\Services\GameLoader
      autowire: true

    game_logger:
      class: AppBundle\Services\GameLogger
      arguments: ['%karoroot%/logs']

    game_inconsistency_finder:
      class: AppBundle\Services\GameInconsistencyFinder
      autowire: true

    game_checker:
      class: AppBundle\Services\GameChecker
      autowire: true

    game_finisher:
      class: AppBundle\Services\GameFinisher
      arguments:
        - '@doctrine.orm.default_entity_manager'
        - '@logger'
        - '@event_dispatcher'

    usermap_voter:
        class: AppBundle\Security\UserMapVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
               - { name: security.voter }

    smilifier:
      class: AppBundle\Services\Smilifier
      arguments:
        - '@smiley_holder'
        - '@logger'

    smiley_holder:
      class: AppBundle\Services\SmileyHolder
      public: false
      arguments:
        - '%kernel.cache_dir%'
        - '%smiley_dir%'
        - '@logger'
      tags:
        - { name: 'kernel.cache_clearer' }
        - { name: 'kernel.cache_warmer' }

    chat_service:
      class: AppBundle\Services\ChatService
      arguments:
        - '%chat%' #config
        - '@doctrine'
        - '@message_normalizer'
        - '@legacy_chatline_converter'
        - '@event_dispatcher'
        - '@snc_redis.default'
        - '@logger'

    chatlog_importer:
      class: AppBundle\Services\ChatlogImporter
      arguments:
        - '@doctrine.orm.default_entity_manager'
        - '@chat_service'
        - '@smilifier'
        - '@legacy_chatline_converter'
        - '@logger'

    realtime_push:
        class: AppBundle\Services\RealtimePush
        autowire: true
        tags:
          - { name: kernel.event_listener, event: chat_message}

    message_normalizer:
      class: AppBundle\Services\MessageNormalizer
      arguments:
        - '@logger'

