# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        #public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    AppBundle\Twig\:
        resource: '../../src/AppBundle/Twig'
        autowire: true
        autoconfigure: true

    AppBundle\Chat\:
        resource: '../../src/AppBundle/Chat'
        autowire: true
        autoconfigure: true

    AppBundle\Game\:
        resource: '../../src/AppBundle/Game'
        autowire: true
        autoconfigure: true

    AppBundle\Tracker\:
        resource: '../../src/AppBundle/Tracker'
        autowire: true
        autoconfigure: true

    AppBundle\Serializer\:
        resource: '../../src/AppBundle/Serializer'
        autowire: true
        autoconfigure: true

    AppBundle\Formatter\:
        resource: '../../src/AppBundle/Formatter'
        autowire: true
        autoconfigure: true

    AppBundle\Http\:
        resource: '../../src/AppBundle/Http'
        autowire: true
        autoconfigure: true

    AppBundle\Messaging\:
        resource: '../../src/AppBundle/Messaging'
        autowire: true
        autoconfigure: true

    AppBundle\Realtime\:
        resource: '../../src/AppBundle/Realtime'
        autowire: true
        autoconfigure: true

    #AppBundle\Services\:
        #resource: '../../src/AppBundle/Services/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        #exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    #AppBundle\:
        #resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        #exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'

    AppBundle\Twig\CachebustExtension:
        arguments:
          $webpath: '%kernel.project_dir%/web'

    AppBundle\Services\ConfigService:
      arguments:
        $config: "%config%"

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    legacy_cookie_authenticator:
        class: AppBundle\Security\LegacyCookieAuthenticator
        autowire: true

    legacy_cookie_setter:
        class: AppBundle\Security\LegacyCookieSetter
        arguments: ['%host%']

    legacy_route_loader:
        class: AppBundle\Services\LegacyRouteLoader
        arguments: ['%karoroot%']
        tags:
          - { name: routing.loader }

    karo_query:
        class: AppBundle\Services\KaroQuery
        autowire: true

    user_repository:
      class: Doctrine\ORM\EntityRepository
      factory: ['@doctrine.orm.default_entity_manager', getRepository]
      arguments:
          - 'AppBundle:User'

    user_distance_calculator:
      class: AppBundle\Services\User\DistanceCalculator
      autowire: true

    usermap_voter:
        class: AppBundle\Security\UserMapVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
               - { name: security.voter }

    AppBundle\Formatter\SmileyHolder:
      arguments:
        - '%kernel.cache_dir%'
        - '%smiley_dir%'
        - '@logger'
      tags:
        - { name: 'kernel.cache_clearer' }
        - { name: 'kernel.cache_warmer' }

    message_normalizer:
      class: AppBundle\Services\MessageNormalizer
      arguments:
        - '@logger'

