# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    legacy_cookie_authenticator:
        class: AppBundle\Security\LegacyCookieAuthenticator
        autowire: true

    legacy_cookie_setter:
        class: AppBundle\Security\LegacyCookieSetter
        arguments: ['%host%']

    legacy_route_loader:
        class: AppBundle\Services\LegacyRouteLoader
        arguments: ['%karoroot%']
        tags:
          - { name: routing.loader }

    visit_log:
        class: AppBundle\Services\VisitLogService
        autowire: true
        tags:
          - { name: kernel.event_listener, event: security.authentication.success}

    game_manager:
      class: AppBundle\Services\GameManager
      autowire: true

    game_logger:
      class: AppBundle\Services\GameLogger
      arguments: ['%karoroot%/logs']

    game_inconsistency_finder:
      class: AppBundle\Services\GameInconsistencyFinder
      autowire: true

    game_checker:
      class: AppBundle\Services\GameChecker
      autowire: true

    game_finisher:
      class: AppBundle\Services\GameFinisher
      arguments:
        - '@doctrine.orm.default_entity_manager'
        - '@logger'
        - '@event_dispatcher'

    usermap_voter:
        class: AppBundle\Security\UserMapVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
               - { name: security.voter }

    smilifier:
      class: AppBundle\Services\Smilifier
      arguments:
        - '@smiley_holder'
        - '@logger'

    smiley_holder:
      class: AppBundle\Services\SmileyHolder
      public: false
      arguments:
        - '%kernel.cache_dir%'
        - '%smiley_dir%'
        - '@logger'
      tags:
        - { name: 'kernel.cache_clearer' }
        - { name: 'kernel.cache_warmer' }

    chat_service:
      class: AppBundle\Services\ChatService
      arguments:
        - '%chat%'
        - '@doctrine'
        - '@event_dispatcher'
        - '@snc_redis.default'
        - '@logger'


    twig.extension.last_chat_message:
      class: AppBundle\Twig\ChatMessageExtension
      arguments:
        - '@chat_service'
      tags:
       - { name: 'twig.extension' }

    twig.extension.date:
        class: AppBundle\Twig\DateExtension
        tags:
             - { name: 'twig.extension' }
