# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    legacy_cookie_authenticator:
        class: AppBundle\Security\LegacyCookieAuthenticator
        autowire: true

    legacy_route_loader:
        class: AppBundle\Services\LegacyRouteLoader
        arguments: [%karoroot%]
        tags:
          - { name: routing.loader }

    visit_log:
        class: AppBundle\Services\VisitLogService
        autowire: true
        tags:
          - { name: kernel.event_listener, event: security.authentication.success}

    game_manager:
      class: AppBundle\Services\GameManager
      autowire: true

    game_logger:
      class: AppBundle\Services\GameLogger
      arguments: [%karoroot%/logs]



